- hosts: proxy
  become: true
  become_user: root
  become_method: sudo
  roles:
    - proxy
    - node_exporter

- hosts: db01 db02
  become: true
  become_user: root
  become_method: sudo
  roles:
    - mysql
    - node_exporter

- hosts: wordpress
  become: true
  become_user: root
  become_method: sudo
  roles:
    - wordpress
    - node_exporter

- hosts: gitlab
  become: true
  become_user: root
  become_method: sudo
  roles:
    - gitlab
    - node_exporter
  environment:
    GITLAB_ROOT_PASSWORD: "{{ gitlab_initial_root_password }}"
    GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "{{ gitlab_runners_registration_token }}"

- hosts: runner
  become: true
  become_user: root
  become_method: sudo
  roles:
    - runner
    - node_exporter

- hosts: monitoring
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus
    - node_exporter
    - alertmanager
    - grafana
